# Generated by Django 4.1.7 on 2023-03-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='2023-03-03 09:53:42.985548', max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('origin_url', models.URLField(verbose_name='origin_url')),
                ('url_hash', models.CharField(max_length=6)),
            ],
            options={
                'verbose_name': 'Visitor link',
                'verbose_name_plural': 'Visitor links',
            },
        ),
    ]
