# Generated by Django 4.1.7 on 2023-03-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorurl',
            name='unique_visitor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visitorurl',
            name='name',
            field=models.CharField(blank=True, default='2023-03-03 10:24:38.176584', max_length=255),
        ),
    ]
